-- AlterTable
ALTER TABLE `final_documents` ADD COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `type` ENUM('TP_APPLICATION', 'REPORT', 'LESSON_PLAN', 'SUPERVISION_VISIT', 'FINAL_DOCUMENT') NOT NULL DEFAULT 'FINAL_DOCUMENT';
